# Generated by Django 3.0.6 on 2020-07-25 19:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Минимальная длина текста 5 символов')], verbose_name='Заголовок')),
                ('content', models.TextField(validators=[django.core.validators.MaxLengthValidator(limit_value=250, message='Максимальная длина текста 250 символов')], verbose_name='Описание')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': ('Статья',),
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
